#pragma once
#include <SDL.h>

// Glyph atlas: 16-column grid of 8x12 cells, generated by
// tools/generate_glyph_atlas.py by rasterizing assets/fonts/TerminalVector.ttf
// (a public-domain vector recreation of the classic Windows "Terminal" 8x12
// console font). 480 glyphs: the first 256 are CP437 in standard byte order,
// followed by 224 extra glyphs (Cyrillic, extra Latin letters, box-drawing/
// shading variants) the font also covers. Glyph N lives at cell
// (N % kGridCols, N / kGridCols). See core/glyph_atlas_data.h for the actual
// generated glyph count (kGlyphAtlasGlyphCount).
constexpr int kGlyphW = 8;
constexpr int kGlyphH = 12;
constexpr int kGridCols = 16;

SDL_Rect glyphSrcRect(int glyphIndex);

// Total number of glyphs actually baked into the atlas (see
// core/glyph_atlas_data.h) -- 480 as of the TerminalVector font, but callers
// should use this rather than assuming a fixed count.
int glyphAtlasGlyphCount();

// Loads the atlas from the compiled-in byte array (core/glyph_atlas_data.h)
// rather than a file on disk, so the built binary is self-contained. Color-
// keys black as transparent and sets nearest-neighbor scaling. Returns
// nullptr on failure (check SDL_GetError()).
SDL_Texture* loadGlyphAtlas(SDL_Renderer* renderer);
