// Generated by tools/generate_glyph_atlas.py -- do not edit by hand.
// Declarations for the embedded glyph-atlas BMP; the bytes themselves live in
// glyph_atlas_data.cpp so this stays a lightweight header (see terminal_8x12.bmp
// for a viewable copy of the same image). Embedded so the atlas ships inside
// the binary instead of needing a companion file on disk.
#pragma once

extern const int kGlyphAtlasGlyphCount;
extern const unsigned int kGlyphAtlasBmpSize;
extern const unsigned char kGlyphAtlasBmpData[];
