#!/usr/bin/env python3
"""
One-time asset-generation tool: rasterizes assets/fonts/TerminalVector.ttf
(a public-domain vector recreation of the classic Windows "Terminal" 8x12
console font -- see TerminalVector.ttf.LICENSE.txt) into a glyph atlas BMP,
laid out as a 16-column grid of 8x12 cells. Glyph N lives at cell
(N % 16, N // 16).

480 glyphs total: the first 256 are CP437 in standard byte order (index N
is CP437 byte N, so this half behaves exactly like the old VGA-font atlas
did), followed by 224 extra Latin-based glyphs the font also happens to
cover (Central/European accented letters, a few symbols) in sorted
codepoint order, purely for extra visual variety in the rain effect.

The font is rendered at its native pixel size (confirmed via inspection to
render as exactly 8x12 with zero antialiasing -- every pixel is fully on or
off, not a partial-coverage gray), so no thresholding step is needed, only
an explicit >127 binarize for robustness.

BMP is used (rather than PNG) purely for visual verification (open it in an
image viewer) -- it is not read by any code at runtime. The actual runtime
asset is the emitted C++ header (a compiled-in byte array), so the built
binary needs no companion font/image file on disk.

Requires: Pillow (`pip install Pillow`)

Run manually whenever the source font changes:
    python3 tools/generate_glyph_atlas.py
"""

import struct
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
FONT_FILE = REPO_ROOT / "assets" / "fonts" / "TerminalVector.ttf"
OUTPUT_BMP = REPO_ROOT / "assets" / "fonts" / "terminal_8x12.bmp"
OUTPUT_HEADER = REPO_ROOT / "core" / "glyph_atlas_data.h"
OUTPUT_SOURCE = REPO_ROOT / "core" / "glyph_atlas_data.cpp"

GLYPH_W = 8
GLYPH_H = 12
GRID_COLS = 16
FONT_SIZE = 12  # renders at exactly 8x12 per glyph at this pixel size


def build_glyph_codepoints():
    """First 256 = CP437 in byte order, then 224 extra codepoints the font
    also covers, in sorted order, appended after."""
    cp437 = [ord(bytes([b]).decode("cp437")) for b in range(256)]

    font = ImageFont.truetype(str(FONT_FILE), size=FONT_SIZE)
    # Pillow doesn't expose cmap directly; go via fontTools if available,
    # otherwise fall back to just the 256 CP437 codepoints.
    try:
        from fontTools.ttLib import TTFont
        cmap = TTFont(str(FONT_FILE)).getBestCmap()
        extra = sorted(set(cmap.keys()) - set(cp437))
    except ImportError:
        print("fontTools not available -- skipping the 224 extra glyphs, "
              "using only the 256 CP437 codepoints. `pip install fonttools` "
              "to include them.")
        extra = []

    return cp437 + extra


def render_glyph_pixels(font, codepoint):
    """Returns an 8x12 list of rows, each a list of booleans (True = lit)."""
    img = Image.new("L", (GLYPH_W, GLYPH_H), 0)
    draw = ImageDraw.Draw(img)
    try:
        draw.text((0, 0), chr(codepoint), font=font, fill=255)
    except Exception:
        pass  # leave blank if the glyph can't be drawn for some reason

    pixels = list(img.getdata())
    return [
        [pixels[y * GLYPH_W + x] > 127 for x in range(GLYPH_W)]
        for y in range(GLYPH_H)
    ]


def build_bmp_bytes(width: int, height: int, pixels) -> bytes:
    """pixels: list of rows (top-to-bottom), each a list of (r,g,b) tuples."""
    row_size = (width * 3 + 3) & ~3  # rows padded to 4-byte boundary
    pixel_data_size = row_size * height
    file_size = 54 + pixel_data_size

    header = struct.pack("<2sIHHI", b"BM", file_size, 0, 0, 54)
    dib_header = struct.pack(
        "<IiiHHIIiiII",
        40,          # DIB header size
        width,
        height,      # positive = bottom-up rows
        1,           # planes
        24,          # bpp
        0,           # no compression
        pixel_data_size,
        2835, 2835,  # ~72 DPI
        0, 0,        # palette
    )

    body = bytearray()
    for row in reversed(pixels):  # BMP rows are stored bottom-to-top
        row_bytes = bytearray()
        for (r, g, b) in row:
            row_bytes += bytes((b, g, r))  # BMP is BGR
        row_bytes += bytes(row_size - len(row_bytes))
        body += row_bytes

    return header + dib_header + bytes(body)


def write_data(header_path: Path, source_path: Path, bmp_bytes: bytes, num_glyphs: int):
    """Emits a lightweight declarations header plus a .cpp holding the actual
    byte array, so the ~8k-line data block isn't dragged into every translation
    unit that only needs the atlas API."""
    header_lines = [
        "// Generated by tools/generate_glyph_atlas.py -- do not edit by hand.",
        "// Declarations for the embedded glyph-atlas BMP; the bytes themselves",
        "// live in glyph_atlas_data.cpp so this stays a lightweight header (see",
        "// terminal_8x12.bmp for a viewable copy of the same image). Embedded so",
        "// the atlas ships inside the binary instead of a companion file on disk.",
        "#pragma once",
        "",
        "extern const int kGlyphAtlasGlyphCount;",
        "extern const unsigned int kGlyphAtlasBmpSize;",
        "extern const unsigned char kGlyphAtlasBmpData[];",
        "",
    ]
    header_path.write_text("\n".join(header_lines), encoding="utf-8")

    source_lines = [
        "// Generated by tools/generate_glyph_atlas.py -- do not edit by hand.",
        "// Raw bytes of the glyph atlas BMP (see terminal_8x12.bmp for a viewable",
        "// copy of the same image), embedded so the atlas ships inside the binary",
        "// instead of needing a companion file on disk. Declared in the header.",
        '#include "glyph_atlas_data.h"',
        "",
        f"const int kGlyphAtlasGlyphCount = {num_glyphs};",
        f"const unsigned int kGlyphAtlasBmpSize = {len(bmp_bytes)};",
        "const unsigned char kGlyphAtlasBmpData[] = {",
    ]
    for i in range(0, len(bmp_bytes), 16):
        chunk = bmp_bytes[i:i + 16]
        source_lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    source_lines.append("};")
    source_lines.append("")

    source_path.write_text("\n".join(source_lines), encoding="utf-8")


def main():
    codepoints = build_glyph_codepoints()
    num_glyphs = len(codepoints)
    grid_rows = (num_glyphs + GRID_COLS - 1) // GRID_COLS
    atlas_w = GLYPH_W * GRID_COLS
    atlas_h = GLYPH_H * grid_rows

    font = ImageFont.truetype(str(FONT_FILE), size=FONT_SIZE)

    white = (255, 255, 255)
    black = (0, 0, 0)
    pixels = [[black] * atlas_w for _ in range(atlas_h)]

    for glyph_index, codepoint in enumerate(codepoints):
        cell_col = glyph_index % GRID_COLS
        cell_row = glyph_index // GRID_COLS
        origin_x = cell_col * GLYPH_W
        origin_y = cell_row * GLYPH_H

        glyph_pixels = render_glyph_pixels(font, codepoint)
        for y in range(GLYPH_H):
            for x in range(GLYPH_W):
                pixels[origin_y + y][origin_x + x] = white if glyph_pixels[y][x] else black

    bmp_bytes = build_bmp_bytes(atlas_w, atlas_h, pixels)

    OUTPUT_BMP.write_bytes(bmp_bytes)
    print(f"Wrote {OUTPUT_BMP} ({atlas_w}x{atlas_h}, {num_glyphs} glyphs)")

    write_data(OUTPUT_HEADER, OUTPUT_SOURCE, bmp_bytes, num_glyphs)
    print(f"Wrote {OUTPUT_HEADER} + {OUTPUT_SOURCE} "
          f"({len(bmp_bytes)} bytes embedded, {num_glyphs} glyphs)")


if __name__ == "__main__":
    main()
